changelog:
  exclude:
    labels:
      - wontfix
  categories:
    - title: Exciting New Features 🎉
      labels:
        - Testing
    - title: Bug Fixes 🛠
      labels:
        - duplicate
    - title: Misc Changes 🔎
      labels:
        - "*"
