changelog:
  exclude:
    labels:
      - wontfix
  categories:
    - title: Breaking Changes 🛠
      labels:
        - duplicate
    - title: Exciting New Features 🎉
      labels:
        - Testing
    - title: Other Changes
      labels:
        - "*"
