name: Tag update and create release
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release to be tagged as'
        required: true
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo The tag is ${{ github.event.inputs.tag }}