name: Tag update and create release
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo The tag is ${{ github.event.inputs.tag }}